### ISSUE TITLE
Request signing is broken

### ISSUE THREAD

**Issue by tostiheld** [99designs/http-signatures-guzzlehttp#9]
Hello,

My requests are simply not being signed when I make them.

Steps to reproduce:
Install the composer package in a Laravel project.
Put this code in a route of a Laravel project:

    $context = new Context([
        'keys' => [ 'name' => 'value' ],
        'algorithm' => 'hmac-sha256',
        'headers' => [ '(request-target)', 'Date', 'Accept' ]
    ]);
    
    $client = new Client();
    $client->getEmitter()->attach(new RequestSubscriber($context));
    
    $response = $client->get('http://localhost:8000/api/test', [
        'headers' => [
            'Date' => date('r'),
            'Accept' => 'application/vnd.vendor.v1+json'
        ],
        'exceptions' => false
    ]);

Start Laravel development server
Request the route in your browser

Expected result:
A response with data from my API endpoint

Actual result:
An error because of missing authorization headers. Upon closer (server side) inspection the headers are indeed not added to the request.

I also noticed your readme is out of date. The example does not work (Guzzle syntax is changed?).

**Comment by navitronic** [comment]
Thanks for reporting this. Can I ask what version of Guzzle you are trying this with?

`composer show` should give you the various version numbers of things that you're using.

**Comment by tostiheld** [comment]
So i started over to verify, since i borked the other project. Is it right that this package does not support Laravel 5.2? I executed these commands:

    composer create-project --prefer-dist laravel/laravel signature-test
    cd signature-test
    composer require 99designs/http-signatures-guzzlehttp

The result is that composer can't resolve the requirements to an installable set of packages. I attached the output of composer.
[composer.txt](https://github.com/99designs/http-signatures-guzzlehttp/files/247170/composer.txt)

**Comment by navitronic** [comment]
Thanks for the information. Seems like there are two separate issues at play here.

I think the installation issue with Laravel 5.2 is because it's installing `v3.0+` of the symfony components that it uses. Looking at Laravel on packagist suggests that it would work with either `2.8.*|3.0.*` of symfony, so theoretically you could require `symfony/http-foundation:2.8` and it should resolve the dependencies. However, I will create an issue try and fix our version constraints, as I am sure others will run into this.

With regards to laravel 4.2, how are you verifying that the request isn't signed?

**Comment by tostiheld** [comment]
nc -l is enough to see the headers - my 4.2 install echos the correct headers but anything else does not. i can post a log if you want, but you can easily test this  yourself.

**Comment by navitronic** [comment]
Turns out that the lack of signing was fixed in master, but I had not released the change.

I've just released `v1.2.1` to include this change, which should solve the originally reported issue.

The inability to install this library with Laravel 5.2 should now be solved via `2.0.3` of `99designs/http-signatures`

Let me know if you have any issues with these changes.
